#!/bin/bash

           clear="\033[0m"
           white="\033[1;37m"
             red="\033[1;31m"
            gold="\033[1;33m"
           green="\033[1;32m"
            cyan="\033[1;36m"
            blue="\033[1;34m"
          purple="\033[1;35m"

          colecho()
          {
              color="$1"
              shift 1
              printf "${!color}${@}${clear}\n"
              return 0
          }

          texteditor=$(which "kate")
          [ "$texteditor" = "" ] && texteditor=$(which "gedit")
          [ "$texteditor" = "" ] && texteditor=$(which "subl")
          [ "$texteditor" = "" ] && texteditor=$(which "eclipse")
          [ "$texteditor" = "" ] && texteditor=$(which "code")
          [ "$texteditor" = "" ] && texteditor=$(which "geany")

             cws="$(realpath "$BASH_SOURCE")"
             cwd="${cws%/*}"
             top="${cwd%/*}"

   top_code_name="code"
      debug_name="debug"
        dep_name="dep"
        exe_prfx="play"
        exe_sufx="run"
        exe_name="${exe_prfx}.${exe_sufx}"

    top_code_dir="${top}/${top_code_name}"
         dep_dir="${cwd}/dep"

trigger_dbg_file="${dep_dir}/${debug_name}"
        exe_file="${top}/${exe_name}"
        exe_path="${top}"
      exe_target="${exe_path}/${exe_prfx}"

         staticA="${dep_dir}/fellowship.a"


alias  builder="${cwd}/builder.sh"
alias    clean="${cwd}/clean.sh"
alias   create="${cwd}/create.sh"
alias    cedit="${cwd}/edit.sh"
alias    fsysc="${cwd}/findsyscall"
alias   linkup="${cwd}/linkup.sh"
alias  looksys="${cwd}/lookupsyscall"
alias  pattern="${cwd}/pattern.sh"
alias    unify="${cwd}/unify.sh"

alias  compile='create'
alias      run="$exe_file"

alias             c='compile'
alias             e='cedit'
alias             g='gdb '"$exe_file"
alias             r='run'
alias             t="if [ -f \"${trigger_dbg_file}\" ]; then rm -f \"${trigger_dbg_file}\"; ${cwd}/clean.sh; else touch \"${trigger_dbg_file}\"; ${cwd}/clean.sh; fi; ls \"${dep_dir}\" | grep \"${debug_name}$\""



# STRINGENT CONSTRAINTS ON 'rm' TO AVOID PROJECT DELETION
RM()
{
  for object in "$@"
  do
    if [ -L "$object" ] ||
     { [ -d "$object" ] && [ "$(ls -A "$object")" = "" ]; } ||
     { [ -f "$object" ] && echo "$object" | grep -q '\(\.[ao]\|sha256\)$'; }
    then
        if [ -L "$object" ] # is a LINK
      then
        colecho gold "[*] removing LINK --> ${object##*Desktop/}"
        rm -f "$object"
      elif [ -f "$object" ] # is a FILE
      then
        colecho gold "[*] removing FILE ==> ${object##*/}"
        rm -f "$object"
      elif [ -d "$object" ] # is an EMPTY DIRECTORY
      then
        colecho gold "[*] removing  DIR []> ${object##*/}"
        rmdir "$object"
      fi
    fi
  done

  return 0
}

# end of source file
